PruebaGeurysJLandeta(CRUD)/Controllers/CustomerController.cs
using PruebaGeurysJLandeta_CRUD_.Models;
using PruebaGeurysJLandeta_CRUD_.Models.Data;
using System;
using System.Data.Entity;

using System.Linq;
using System.Web.Mvc;

namespace PruebaGeurysJLandeta_CRUD_.Controllers
{
    public class CustomerController : Controller
    {
        private readonly TestInvoiceDbContext _dbContext = new TestInvoiceDbContext();
        
        public ActionResult Index()
        {
            var data = _dbContext.Customers.Where(c => c.Status == true).ToList();
            return View(data);
        }
        public ActionResult AddCustomer()
        {
            Customer customer = new Customer
            {
                Status = true
            };

            return View(customer);
        }
        [HttpPost]
        public ActionResult AddCustomer(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var datos = _dbContext.Customers.Add(customer);
                    _dbContext.SaveChanges();

                    return Redirect("/Customer/Index");
                }

                return View(customer);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult EditCustomer(int id)
        {
            var data = _dbContext.Customers.Find(id);
            Customer model = new Customer()
            {
                Adress = data.Adress,
                CustName = data.CustName,
                CustomerTypeId = data.CustomerTypeId,
                Status = data.Status,
                Id = id
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditCustomer(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _dbContext.Customers.Find(customer.Id);

                    data.Adress = customer.Adress;
                    data.CustName = customer.CustName;
                    data.CustomerTypeId = customer.CustomerTypeId;
                    data.Status = customer.Status;
                    data.Id = customer.Id;
                    
                    _dbContext.Entry(data).State = EntityState.Modified;
                    _dbContext.SaveChanges();

                    return Redirect("/Customer/Index");
                }

                return View(customer);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        [HttpGet]
        public ActionResult DeleteCustomer(Customer customer)
        {
            try
            {
                var data = _dbContext.Customers.Find(customer.Id);

                data.Status = false;

                _dbContext.Entry(data).State = EntityState.Modified;
                _dbContext.SaveChanges();

                return Redirect("/Customer/Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

PruebaGeurysJLandeta(CRUD)/Controllers/CustomerTypeController.cs
using PruebaGeurysJLandeta_CRUD_.Models;
using PruebaGeurysJLandeta_CRUD_.Models.Data;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaGeurysJLandeta_CRUD_.Controllers
{
    public class CustomerTypeController : Controller
    {
        private readonly TestInvoiceDbContext _dbContext = new TestInvoiceDbContext();
        public ActionResult Index()
        {
            var data = _dbContext.CustomerTypes.ToList();
            return View(data);
        }

        public ActionResult AddCustomerType()
        {
            CustomerType customerType = new CustomerType();
            return View(customerType);
        }
        [HttpPost]
        public ActionResult AddCustomerType(CustomerType customerType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var datos = _dbContext.CustomerTypes.Add(customerType);
                    _dbContext.SaveChanges();

                    return Redirect("/CustomerType/Index");
                }

                return View(customerType);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        public ActionResult EditCustomerType(int id)
        {
            var data = _dbContext.CustomerTypes.Find(id);
            CustomerType model = new CustomerType()
            {
                Id = data.Id,
                Description = data.Description
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult EditCustomerType(CustomerType customerType)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _dbContext.CustomerTypes.Find(customerType.Id);

                    data.Description = customerType.Description;

                    _dbContext.Entry(data).State = EntityState.Modified;
                    _dbContext.SaveChanges();

                    return Redirect("/CustomerType/Index");
                }

                return View(customerType);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        [HttpGet]
        public ActionResult DeleteCustomerType(CustomerType customerType)
        {
            try
            {
                var data = _dbContext.CustomerTypes.Find(customerType.Id);

                _dbContext.CustomerTypes.Remove(data);
                _dbContext.SaveChanges();

                return Redirect("/CustomerType/Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

    }
}

PruebaGeurysJLandeta(CRUD)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD", "Customer", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customer", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Customer Type", "Index", "CustomerType")</li>
                    <li>@Html.ActionLink("Invoice", "Index", "Invoice")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>